use std::fmt::Display;
use std::str::FromStr;

#[derive(Debug, Copy, Clone, Hash, PartialOrd, PartialEq, Eq)]
pub enum ClaimProperties {
    //Paid Creds
    AccountName,
    DomainName,
    //Sitepass
    SitePass,
    //Honestbot
    Honestbot0,
    //NotBots
    Notbot0,
    Notbot1,
    Notbot2,
    //SignatureLicense
    SignatureLicense,
    //PII
    GivenNames,
    FamilyName,
    FirstName,
    Gender,
    Nationality,
    BirthDate,
    BirthDay,
    BirthMonth,
    BirthYear,
    //AgeCredentials
    Age,
    AgeOver13,
    AgeOver14,
    AgeOver15,
    AgeOver16,
    AgeOver17,
    AgeOver18,
    AgeOver19,
    AgeOver20,
    AgeOver21,
    AgeOver22,
    AgeOver23,
    AgeOver24,
    AgeOver25,
    AgeOver100,
    AgeRange20To24,
    AgeRange25To29,
    AgeRange30To34,
    AgeRange35To39,
    AgeRange40To44,
    AgeRange45To49,
    AgeRange50To54,
    AgeRange55To59,
    AgeRange60To64,
    AgeRange65To69,
    AgeRange70To74,
    AgeRange75To79,
    AgeRange80To84,
    AgeRange85To89,
    AgeRange90To94,
    AgeRange95To99,
    AgeRange20To29,
    AgeRange30To39,
    AgeRange40To49,
    AgeRange50To59,
    AgeRange60To69,
    AgeRange70To79,
    AgeRange80To89,
    AgeRange90To99,
}
impl Display for ClaimProperties {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
impl ClaimProperties {
    pub fn as_str(&self) -> &'static str {
        match self {
            ClaimProperties::AccountName => "sha2-256|CBOR://./v1/account_name",
            ClaimProperties::DomainName => "sha2-256|CBOR://./v1/domain_name",
            ClaimProperties::SignatureLicense => "notbot://./v1/signature_license",
            ClaimProperties::SitePass => "julia://./v1/site_pass",
            ClaimProperties::Honestbot0 => "notbot://./v1/honestbot0",
            ClaimProperties::Notbot0 => "notbot://./v1/notbot0",
            ClaimProperties::Notbot1 => "notbot://./v1/notbot1",
            ClaimProperties::Notbot2 => "notbot://./v1/notbot2",
            ClaimProperties::FirstName => "julia://./v1/pii/first_name",
            ClaimProperties::GivenNames => "julia://./v1/pii/given_names",
            ClaimProperties::FamilyName => "julia://./v1/pii/family_name",
            ClaimProperties::Gender => "julia://./v1/pii/gender",
            ClaimProperties::Nationality => "julia://./v1/pii/nationality",
            ClaimProperties::BirthDate => "julia://./v1/pii/date_of_birth",
            ClaimProperties::BirthDay => "julia://./v1/pii/birth_day",
            ClaimProperties::BirthMonth => "julia://./v1/pii/birth_month",
            ClaimProperties::BirthYear => "julia://./v1/pii/birth_year",
            ClaimProperties::Age => "julia://./v1/pii/age",
            ClaimProperties::AgeOver13 => "julia://./v1/pii/age_over_13",
            ClaimProperties::AgeOver14 => "julia://./v1/pii/age_over_14",
            ClaimProperties::AgeOver15 => "julia://./v1/pii/age_over_15",
            ClaimProperties::AgeOver16 => "julia://./v1/pii/age_over_16",
            ClaimProperties::AgeOver17 => "julia://./v1/pii/age_over_17",
            ClaimProperties::AgeOver18 => "julia://./v1/pii/age_over_18",
            ClaimProperties::AgeOver19 => "julia://./v1/pii/age_over_19",
            ClaimProperties::AgeOver20 => "julia://./v1/pii/age_over_20",
            ClaimProperties::AgeOver21 => "julia://./v1/pii/age_over_21",
            ClaimProperties::AgeOver22 => "julia://./v1/pii/age_over_22",
            ClaimProperties::AgeOver23 => "julia://./v1/pii/age_over_23",
            ClaimProperties::AgeOver24 => "julia://./v1/pii/age_over_24",
            ClaimProperties::AgeOver25 => "julia://./v1/pii/age_over_25",
            ClaimProperties::AgeOver100 => "julia://./v1/pii/age_over_100",
            ClaimProperties::AgeRange20To24 => "julia://./v1/pii/age_range_20_24",
            ClaimProperties::AgeRange25To29 => "julia://./v1/pii/age_range_25_29",
            ClaimProperties::AgeRange30To34 => "julia://./v1/pii/age_range_30_34",
            ClaimProperties::AgeRange35To39 => "julia://./v1/pii/age_range_35_39",
            ClaimProperties::AgeRange40To44 => "julia://./v1/pii/age_range_40_44",
            ClaimProperties::AgeRange45To49 => "julia://./v1/pii/age_range_45_49",
            ClaimProperties::AgeRange50To54 => "julia://./v1/pii/age_range_50_54",
            ClaimProperties::AgeRange55To59 => "julia://./v1/pii/age_range_55_59",
            ClaimProperties::AgeRange60To64 => "julia://./v1/pii/age_range_60_64",
            ClaimProperties::AgeRange65To69 => "julia://./v1/pii/age_range_65_69",
            ClaimProperties::AgeRange70To74 => "julia://./v1/pii/age_range_70_74",
            ClaimProperties::AgeRange75To79 => "julia://./v1/pii/age_range_75_79",
            ClaimProperties::AgeRange80To84 => "julia://./v1/pii/age_range_80_84",
            ClaimProperties::AgeRange85To89 => "julia://./v1/pii/age_range_85_89",
            ClaimProperties::AgeRange90To94 => "julia://./v1/pii/age_range_90_94",
            ClaimProperties::AgeRange95To99 => "julia://./v1/pii/age_range_95_99",
            ClaimProperties::AgeRange20To29 => "julia://./v1/pii/age_range_20_29",
            ClaimProperties::AgeRange30To39 => "julia://./v1/pii/age_range_30_39",
            ClaimProperties::AgeRange40To49 => "julia://./v1/pii/age_range_40_49",
            ClaimProperties::AgeRange50To59 => "julia://./v1/pii/age_range_50_59",
            ClaimProperties::AgeRange60To69 => "julia://./v1/pii/age_range_60_69",
            ClaimProperties::AgeRange70To79 => "julia://./v1/pii/age_range_70_79",
            ClaimProperties::AgeRange80To89 => "julia://./v1/pii/age_range_80_89",
            ClaimProperties::AgeRange90To99 => "julia://./v1/pii/age_range_90_99",
        }
    }
}
impl FromStr for ClaimProperties {
    type Err = &'static str;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "sha2-256|CBOR://./v1/account_name" => Ok(ClaimProperties::AccountName),
            "sha2-256|CBOR://./v1/domain_name" => Ok(ClaimProperties::DomainName),
            "notbot://./v1/signature_license" => Ok(ClaimProperties::SignatureLicense),
            "julia://./v1/site_pass" => Ok(ClaimProperties::SitePass),
            "notbot://./v1/honestbot0" => Ok(ClaimProperties::Honestbot0),
            "notbot://./v1/notbot0" => Ok(ClaimProperties::Notbot0),
            "notbot://./v1/notbot1" => Ok(ClaimProperties::Notbot1),
            "notbot://./v1/notbot2" => Ok(ClaimProperties::Notbot2),
            "julia://./v1/pii/first_name" => Ok(ClaimProperties::FirstName),
            "julia://./v1/pii/given_names" => Ok(ClaimProperties::GivenNames),
            "julia://./v1/pii/family_name" => Ok(ClaimProperties::FamilyName),
            "julia://./v1/pii/gender" => Ok(ClaimProperties::Gender),
            "julia://./v1/pii/nationality" => Ok(ClaimProperties::Nationality),
            "julia://./v1/pii/date_of_birth" => Ok(ClaimProperties::BirthDate),
            "julia://./v1/pii/birth_day" => Ok(ClaimProperties::BirthDay),
            "julia://./v1/pii/birth_month" => Ok(ClaimProperties::BirthMonth),
            "julia://./v1/pii/birth_year" => Ok(ClaimProperties::BirthYear),
            "julia://./v1/pii/age" => Ok(ClaimProperties::Age),
            "julia://./v1/pii/age_over_13" => Ok(ClaimProperties::AgeOver13),
            "julia://./v1/pii/age_over_14" => Ok(ClaimProperties::AgeOver14),
            "julia://./v1/pii/age_over_15" => Ok(ClaimProperties::AgeOver15),
            "julia://./v1/pii/age_over_16" => Ok(ClaimProperties::AgeOver16),
            "julia://./v1/pii/age_over_17" => Ok(ClaimProperties::AgeOver17),
            "julia://./v1/pii/age_over_18" => Ok(ClaimProperties::AgeOver18),
            "julia://./v1/pii/age_over_19" => Ok(ClaimProperties::AgeOver19),
            "julia://./v1/pii/age_over_20" => Ok(ClaimProperties::AgeOver20),
            "julia://./v1/pii/age_over_21" => Ok(ClaimProperties::AgeOver21),
            "julia://./v1/pii/age_over_22" => Ok(ClaimProperties::AgeOver22),
            "julia://./v1/pii/age_over_23" => Ok(ClaimProperties::AgeOver23),
            "julia://./v1/pii/age_over_24" => Ok(ClaimProperties::AgeOver24),
            "julia://./v1/pii/age_over_25" => Ok(ClaimProperties::AgeOver25),
            "julia://./v1/pii/age_over_100" => Ok(ClaimProperties::AgeOver100),
            "julia://./v1/pii/age_range_20_24" => Ok(ClaimProperties::AgeRange20To24),
            "julia://./v1/pii/age_range_25_29" => Ok(ClaimProperties::AgeRange25To29),
            "julia://./v1/pii/age_range_30_34" => Ok(ClaimProperties::AgeRange30To34),
            "julia://./v1/pii/age_range_35_39" => Ok(ClaimProperties::AgeRange35To39),
            "julia://./v1/pii/age_range_40_44" => Ok(ClaimProperties::AgeRange40To44),
            "julia://./v1/pii/age_range_45_49" => Ok(ClaimProperties::AgeRange45To49),
            "julia://./v1/pii/age_range_50_54" => Ok(ClaimProperties::AgeRange50To54),
            "julia://./v1/pii/age_range_55_59" => Ok(ClaimProperties::AgeRange55To59),
            "julia://./v1/pii/age_range_60_64" => Ok(ClaimProperties::AgeRange60To64),
            "julia://./v1/pii/age_range_65_69" => Ok(ClaimProperties::AgeRange65To69),
            "julia://./v1/pii/age_range_70_74" => Ok(ClaimProperties::AgeRange70To74),
            "julia://./v1/pii/age_range_75_79" => Ok(ClaimProperties::AgeRange75To79),
            "julia://./v1/pii/age_range_80_84" => Ok(ClaimProperties::AgeRange80To84),
            "julia://./v1/pii/age_range_85_89" => Ok(ClaimProperties::AgeRange85To89),
            "julia://./v1/pii/age_range_90_94" => Ok(ClaimProperties::AgeRange90To94),
            "julia://./v1/pii/age_range_95_99" => Ok(ClaimProperties::AgeRange95To99),
            "julia://./v1/pii/age_range_20_29" => Ok(ClaimProperties::AgeRange20To29),
            "julia://./v1/pii/age_range_30_39" => Ok(ClaimProperties::AgeRange30To39),
            "julia://./v1/pii/age_range_40_49" => Ok(ClaimProperties::AgeRange40To49),
            "julia://./v1/pii/age_range_50_59" => Ok(ClaimProperties::AgeRange50To59),
            "julia://./v1/pii/age_range_60_69" => Ok(ClaimProperties::AgeRange60To69),
            "julia://./v1/pii/age_range_70_79" => Ok(ClaimProperties::AgeRange70To79),
            "julia://./v1/pii/age_range_80_89" => Ok(ClaimProperties::AgeRange80To89),
            "julia://./v1/pii/age_range_90_99" => Ok(ClaimProperties::AgeRange90To99),
            _ => Err("Invalid Claim Property"),
        }
    }
}
